-- begin AUTODEALER_AUTO_DEALER
alter table AUTODEALER_AUTO_DEALER add constraint FK_AUTODEALER_AUTO_DEALER_ON_COUNTRY foreign key (COUNTRY_ID) references AUTODEALER_COUNTRY(ID)^
create unique index IDX_AUTODEALER_AUTO_DEALER_UK_NAME on AUTODEALER_AUTO_DEALER (NAME) where DELETE_TS is null ^
create unique index IDX_AUTODEALER_AUTO_DEALER_UK_COUNTRY_ID on AUTODEALER_AUTO_DEALER (COUNTRY_ID) where DELETE_TS is null ^
create index IDX_AUTODEALER_AUTO_DEALER_ON_COUNTRY on AUTODEALER_AUTO_DEALER (COUNTRY_ID)^
-- end AUTODEALER_AUTO_DEALER
-- begin AUTODEALER_COLOR
create unique index IDX_AUTODEALER_COLOR_UK_NAME on AUTODEALER_COLOR (NAME) where DELETE_TS is null ^
create unique index IDX_AUTODEALER_COLOR_UK_CODE on AUTODEALER_COLOR (CODE) where DELETE_TS is null ^
-- end AUTODEALER_COLOR
-- begin AUTODEALER_CAR_BRAND
alter table AUTODEALER_CAR_BRAND add constraint FK_AUTODEALER_CAR_BRAND_ON_EQUIPMENT foreign key (EQUIPMENT_ID) references AUTODEALER_EQUIPMENT(ID)^
alter table AUTODEALER_CAR_BRAND add constraint FK_AUTODEALER_CAR_BRAND_ON_AUTO_DEALER foreign key (AUTO_DEALER_ID) references AUTODEALER_AUTO_DEALER(ID)^
create index IDX_AUTODEALER_CAR_BRAND_ON_EQUIPMENT on AUTODEALER_CAR_BRAND (EQUIPMENT_ID)^
create index IDX_AUTODEALER_CAR_BRAND_ON_AUTO_DEALER on AUTODEALER_CAR_BRAND (AUTO_DEALER_ID)^
-- end AUTODEALER_CAR_BRAND
-- begin AUTODEALER_CAR
alter table AUTODEALER_CAR add constraint FK_AUTODEALER_CAR_ON_AUTO_DEALER foreign key (AUTO_DEALER_ID) references AUTODEALER_AUTO_DEALER(ID)^
alter table AUTODEALER_CAR add constraint FK_AUTODEALER_CAR_ON_CAR_BRAND foreign key (CAR_BRAND_ID) references AUTODEALER_CAR_BRAND(ID)^
alter table AUTODEALER_CAR add constraint FK_AUTODEALER_CAR_ON_EQUIPMENT foreign key (EQUIPMENT_ID) references AUTODEALER_EQUIPMENT(ID)^
create index IDX_AUTODEALER_CAR_ON_AUTO_DEALER on AUTODEALER_CAR (AUTO_DEALER_ID)^
create index IDX_AUTODEALER_CAR_ON_CAR_BRAND on AUTODEALER_CAR (CAR_BRAND_ID)^
create index IDX_AUTODEALER_CAR_ON_EQUIPMENT on AUTODEALER_CAR (EQUIPMENT_ID)^
-- end AUTODEALER_CAR
