-- begin AUTODEALER_AUTO_DEALER
alter table AUTODEALER_AUTO_DEALER add constraint FK_AUTODEALER_AUTO_DEALER_ON_COUNTRY foreign key (COUNTRY_ID) references AUTODEALER_COUNTRY(ID)^
create unique index IDX_AUTODEALER_AUTO_DEALER_UK_NAME on AUTODEALER_AUTO_DEALER (NAME) where DELETE_TS is null ^
create unique index IDX_AUTODEALER_AUTO_DEALER_UK_COUNTRY_ID on AUTODEALER_AUTO_DEALER (COUNTRY_ID) where DELETE_TS is null ^
create index IDX_AUTODEALER_AUTO_DEALER_ON_COUNTRY on AUTODEALER_AUTO_DEALER (COUNTRY_ID)^
-- end AUTODEALER_AUTO_DEALER
