alter table AUTODEALER_CAR_BRAND add constraint FK_AUTODEALER_CAR_BRAND_ON_EQUIPMENT foreign key (EQUIPMENT_ID) references AUTODEALER_EQUIPMENT(ID);
alter table AUTODEALER_CAR_BRAND add constraint FK_AUTODEALER_CAR_BRAND_ON_AUTO_DEALER foreign key (AUTO_DEALER_ID) references AUTODEALER_AUTO_DEALER(ID);
create index IDX_AUTODEALER_CAR_BRAND_ON_EQUIPMENT on AUTODEALER_CAR_BRAND (EQUIPMENT_ID);
create index IDX_AUTODEALER_CAR_BRAND_ON_AUTO_DEALER on AUTODEALER_CAR_BRAND (AUTO_DEALER_ID);
